version = 1

# generated files
[[annotations]]
path = [
    "uv.lock",
    "opal/static/thirdparty/package-lock.json",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "opal/core/tests/fixtures/homer_pharmacy.hl7v2",
    "opal/core/tests/fixtures/marge_NTE.hl7v2",
    "opal/core/tests/fixtures/marge_ORC.hl7v2",
    "opal/core/tests/fixtures/marge_PID.hl7v2",
    "opal/core/tests/fixtures/marge_PV1.hl7v2",
    "opal/core/tests/fixtures/marge_RXC.hl7v2",
    "opal/core/tests/fixtures/marge_RXE.hl7v2",
    "opal/core/tests/fixtures/marge_RXR.hl7v2",
    "opal/core/tests/fixtures/marge_missing_CE_pharmacy.hl7v2",
    "opal/core/tests/fixtures/marge_pharmacy.hl7v2",
    "opal/static/thirdparty/package.json",
    "opal/services/data_processing/tests/fixtures/attributes_expected_signatures.csv",
    "opal/tests/fixtures/test_PDF.pdf",
    "opal/tests/fixtures/test_activity_log.csv",
    "opal/tests/fixtures/test_activity_log_large_data.csv",
    "opal/tests/fixtures/test_data_received_log.csv",
    "opal/tests/fixtures/test_data_received_log_large_data.csv",
    "opal/tests/fixtures/test_data_received_log_no_date.csv",
    "opal/services/fhir/tests/fixtures/*.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
    ".vscode/extensions.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
    ".vscode/launch.json",
    ".vscode/settings.json",
    # avoid users copying copyright headers when copying the .env.sample to .env
    ".env.sample",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2021 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
    "opal/templates/email/verification_code.txt",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "LicenseRef-OpalTrademarks"


[[annotations]]
path = [
    "opal/templates/email/confirmation_email.txt",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "LicenseRef-OpalTrademarks"


[[annotations]]
path = [
    "opal/static/images/favicon.ico",
    "opal/static/images/logo_opal.png",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2015 Ackeem Joseph <ackeem.joseph@muhc.mcgill.ca>"
SPDX-License-Identifier = "LicenseRef-OpalTrademarks"


[[annotations]]
path = [
    "opal/static/thirdparty/bootstrap/css/bootstrap.min.css",
    "opal/static/thirdparty/bootstrap/css/bootstrap.min.css.map",
    "opal/static/thirdparty/bootstrap/js/bootstrap.bundle.min.js",
    "opal/static/thirdparty/bootstrap/js/bootstrap.bundle.min.js.map",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2011-2025 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"


[[annotations]]
path = [
    "opal/static/thirdparty/unpoly/css/unpoly-bootstrap5.min.css",
    "opal/static/thirdparty/unpoly/css/unpoly.min.css",
    "opal/static/thirdparty/unpoly/js/unpoly-bootstrap5.min.js",
    "opal/static/thirdparty/unpoly/js/unpoly.min.js",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2014-2021 Henning Koch"
SPDX-License-Identifier = "MIT"


[[annotations]]
path = [
    "opal/static/thirdparty/fontawesomefree/css/fontawesome.min.css",
    "opal/static/thirdparty/fontawesomefree/css/regular.min.css",
    "opal/static/thirdparty/fontawesomefree/css/solid.min.css",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2024 Fonticons, Inc."
SPDX-License-Identifier = "MIT"


[[annotations]]
path = [
    "opal/static/thirdparty/fontawesomefree/webfonts/fa-regular-400.ttf",
    "opal/static/thirdparty/fontawesomefree/webfonts/fa-regular-400.woff2",
    "opal/static/thirdparty/fontawesomefree/webfonts/fa-solid-900.ttf",
    "opal/static/thirdparty/fontawesomefree/webfonts/fa-solid-900.woff2",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2024 Fonticons, Inc."
SPDX-License-Identifier = "OFL-1.1"


[[annotations]]
path = [
    "opal/core/management/commands/files/ohigph/logo.png",
    "opal/core/management/commands/files/ohigph/terms_of_use_en.pdf",
    "opal/core/management/commands/files/ohigph/terms_of_use_fr.pdf",
    "opal/core/management/commands/files/omi/logo.png",
    "opal/core/management/commands/files/omi/terms_of_use_en.pdf",
    "opal/core/management/commands/files/omi/terms_of_use_fr.pdf",
    "opal/tests/fixtures/test_logo.png",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
